### PR TITLE
fix for issue #20 (frontend fetch does not take store view into account)

### PR DESCRIPTION
**Pull request by lfglopes**

### CODE REVIEW

**Comment by peterjaap** [comment]
Where does `BASE_URL` come from? That is not a globally defined constant?

**Comment by peterjaap** [comment]
:+1:

**Comment by lfglopes** [comment]
Sorry to say, but `url.build` turned out to not work as I expected either... I'll try to find another solution.

Probably will have to pass the base url on the phtml as it seems to be no Javascript-native way of doing this.

**Comment by peterjaap** [comment]
@lfglopes hmm I tried `url.build` in a sandbox and it gave me the results I expected. What didn't exactly work as you thought it would?

**Comment by peterjaap** [comment]
Ah wait, you still have to manually set the baseUrl on the url object.

**Comment by lfglopes** [comment]
Exactly

**Comment by peterjaap** [comment]
Including the base url (fetched through `$block->getBaseUrl()`) in the phtml would be the only way to go as far as I can see. That's also how Magento core does it in for example `vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml`.

**Pull request merged**
